spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/todoistdb}
    username: ${DB_USERNAME:stepan}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver

jwt:
  header: Authorization
  secret: proselyte
  expiration: 604800
#
#  jpa:
#    hibernate:
#      ddl-auto: create
server:
  port: ${SERVER_PORT:8080}